DEBUG = True
SECRETE_KEY = 'secreto'
SQLALCHEMY_DATABASE_URI = "sqlite:///../instance/database.db"
SQLALCHEMY_TRACK_MODIFCATIONS = False
JWT_SECRET_KEY = 'supersecreto'
JWT_BLACKLIST_ENABLED = True
JWT_BLACKLIST_TOKEN_CHECKS= ["access"]